name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      -name: Install ğŸ¦€
        run: |
          yarn

      - name: Lint ğŸ“
        run: |
          yarn lint

      - name: Dry run
        run: |
          yarn deploy
